const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../app-v588.js'),'utf8');
function fn(name){const start=source.search(new RegExp('^(?:async )?function '+name+'\\(', 'm'));assert(start>=0,name);const end=source.indexOf('\n',start),first=source.slice(start,end);return first.endsWith('}')?first:source.slice(start,source.indexOf('\n}',end)+2)}
let today='2026-09-22',kpiStart='2026-01-01',trial=false,holiday=false;
const employees=[{id:'12',shift:'day',startDate:'2026-01-01'},{id:'14',shift:'night',startDate:'2026-01-01'}];
const ctx={Date,Intl,Math,Number,String,employees,thaiDateKey:(d)=>d?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(d):today,kpiPeriodStart:y=>Number(y)<Number(kpiStart.slice(0,4))?null:kpiStart,attendanceIsTrialDate:()=>trial,isHoliday:()=>holiday,findAttendanceEmployeeById:id=>employees.find(e=>String(e.id)===String(id)),employeeShiftKey:emp=>emp.shift,shiftConfig:(emp,date,override)=>({key:override||emp.shift,lateReasonAfter:(override||emp.shift)==='night'?'20:05':'08:05'})};
vm.createContext(ctx);
for(const name of ['validAttendanceDate','attendanceLeaveRetroDays','attendanceKpiResult','attendanceDeduction','attendanceDeductionLabel','attendanceStatus','attendanceLateMinutes','recordLocalMinutes','recordShiftMinutes','timeMinutes','daysSinceThaiDate','employeeEligibleOnDate','medicalCertificateWithinWindow','validateAttendanceNoticeDate','normalizeAttendanceEmployeeId','attendanceEmployeeKey','attendanceEmployeeNumericKey','sameAttendanceEmployeeId','mergeAttendanceRecords'])vm.runInContext(fn(name),ctx);
let count=0;
const base={employeeId:'12',date:today,section:'Test'};
function check(name,rec,points,code){const r=ctx.attendanceKpiResult(rec);assert.equal(r.points,points,name);assert.equal(r.code,code,name);assert.equal(ctx.attendanceDeduction(rec),points,name);assert.equal(ctx.attendanceDeductionLabel(rec),r.label,name);count++}
function leave(type,extra={}){return {...base,exception:{type:'leave',leaveType:type,...extra}}}
check('no row',null,0,'empty');check('missing date',{employeeId:'12'},0,'invalid_date');check('impossible date',{...base,date:'2026-02-30'},0,'invalid_date');check('waiting',{...base},0,'pending');check('late notice without check-in',{...base,lateNotice:{reason:'traffic'}},0,'pending');check('late exception without time',{...base,exception:{type:'late'}},0,'pending');check('absence',{...base,exception:{type:'absent'}},10,'absent');
for(const [employeeId,shift,hour] of [['12','day',8],['14','night',20]])for(const [minute,points,code] of [[5,0,'on_time'],[6,1,'late'],[20,1,'late'],[21,2,'late'],[35,2,'late'],[36,3,'late'],[59,3,'late']]){const rec={...base,employeeId,shift,checkIn:`2026-09-22T${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}:00+07:00`};check(`${shift} ${hour}:${minute}`,rec,points,code);check(`${shift} check-in replaces absence`,{...rec,exception:{type:'absent'}},points,code)}
check('night after midnight',{...base,date:'2026-09-21',employeeId:'14',shift:'night',checkIn:'2026-09-22T01:00:00+07:00'},3,'late');check('invalid checkin',{...base,checkIn:'invalid'},0,'invalid_checkin');
for(const before of [true,false])check('same-day personal before/after cutoff',leave('personal',{advanceSameDay:before}),1,'personal');check('advance personal on leave day',leave('personal',{advanceDays:7,advanceFuture:true}),1,'personal');for(const retroDays of [1,2,3])check(`personal retro ${retroDays}`,leave('personal',{retroDays}),4,'personal_retro');check('personal over 3',leave('personal',{retroDays:4}),10,'personal_overdue');
check('same-day sick no certificate',leave('sick'),1,'sick_pending');check('same-day sick certificate',leave('sick',{medicalCertificate:true}),0,'sick_certificate');for(const retroDays of [1,2,3])for(const medicalCertificate of [true,false])check(`sick retro ${retroDays} cert ${medicalCertificate}`,leave('sick',{retroDays,medicalCertificate}),2,'sick_retro');for(const medicalCertificate of [true,false])check('sick over 3',leave('sick',{retroDays:4,medicalCertificate}),4,'sick_converted');check('converted stored as personal',leave('personal',{retroDays:9,convertedFromSickRetroOver3:true}),4,'sick_converted');
const sameDaySick={...leave('sick'),date:'2026-09-19',exception:{type:'leave',leaveType:'sick',submittedAt:'2026-09-19T10:00:00+07:00'}};check('certificate due day inclusive',sameDaySick,1,'sick_pending');assert.equal(ctx.medicalCertificateWithinWindow(sameDaySick),true);today='2026-09-23';check('certificate missing day 4',sameDaySick,2,'sick_overdue');assert.equal(ctx.medicalCertificateWithinWindow(sameDaySick),false);check('certificate attached on day 3 preserved',{...sameDaySick,exception:{...sameDaySick.exception,medicalCertificate:true,medicalCertificateAttachedAt:'2026-09-22T10:00:00+07:00'}},0,'sick_certificate');today='2026-09-22';
check('derive retro days from submission when cached count is wrong',{...leave('personal',{retroDays:0,submittedAt:'2026-09-22T01:00:00+07:00'}),date:'2026-09-20'},4,'personal_retro');check('Bangkok submission date across UTC midnight',{...leave('personal',{retroDays:0,submittedAt:'2026-09-21T18:00:00Z'}),date:'2026-09-21'},4,'personal_retro');
for(const ex of [{type:'absent'},{type:'leave',leaveType:'personal'},{type:'leave',leaveType:'sick'}])check('future row',{...base,date:'2026-09-23',exception:ex},0,'future');holiday=true;check('holiday absence',{...base,exception:{type:'absent'}},0,'holiday');check('holiday leave',leave('personal'),0,'holiday');holiday=false;trial=true;check('trial absence',{...base,exception:{type:'absent'}},0,'trial');trial=false;kpiStart='2026-09-23';check('before KPI',{...base,exception:{type:'absent'}},0,'before_kpi');kpiStart='2026-01-01';employees[0].startDate='2026-09-23';check('before employment',{...base,exception:{type:'absent'}},0,'before_employment');employees[0].startDate='2026-01-01';
check('leave and checkin use one leave deduction',{...leave('personal'),checkIn:'2026-09-22T09:00:00+07:00'},1,'personal');
for(const date of ['', '2026-02-30','not-date'])assert.throws(()=>ctx.validateAttendanceNoticeDate(date,3,'personal'));
assert.equal(ctx.validateAttendanceNoticeDate('2026-09-19',3,'personal'),3);assert.throws(()=>ctx.validateAttendanceNoticeDate('2026-09-18',3,'personal'));assert.equal(ctx.validateAttendanceNoticeDate('2026-09-29',3,'personal'),-7);assert.throws(()=>ctx.validateAttendanceNoticeDate('2026-09-30',3,'personal'));assert.throws(()=>ctx.validateAttendanceNoticeDate('2026-09-23',3,'sick'));count+=8;
const old={...base,checkIn:'2026-09-22T08:00:00+07:00',updatedAt:'2026-09-22T01:00:00Z'};
for(const type of ['absent','leave','late']){const correction={...base,updatedAt:'2026-09-22T04:00:00Z',exception:{type,manualAdmin:true,leaveType:'personal'},...(type==='late'?{checkIn:'2026-09-22T09:00:00+07:00'}:{})};for(const rows of [[old,correction],[correction,old]]){const merged=ctx.mergeAttendanceRecords([rows[0]],[rows[1]])[0];assert.equal(merged.exception.type,type);assert.equal(merged.checkIn,correction.checkIn);count++}}
for(const name of ['adminAttendanceTimeIso','previewBiometricAttendanceEvent'])vm.runInContext(fn(name),ctx);
assert.equal(ctx.adminAttendanceTimeIso('2026-09-21','01:00','night'),'2026-09-21T18:00:00.000Z');assert.equal(ctx.adminAttendanceTimeIso('2026-09-21','25:00','night'),'');assert.equal(ctx.adminAttendanceTimeIso('2026-02-30','08:00','day'),'');count+=3;
ctx.dateKeyOffsetFrom=(date,offset)=>new Date(Date.parse(date+'T00:00:00Z')+offset*86400000).toISOString().slice(0,10);
ctx.attendanceRecordBlockedByCleanup=()=>false;ctx.attendanceRecordBlockedByDeletion=()=>false;let existing=null;ctx.attendanceFor=()=>existing;
const now=new Date('2026-09-22T23:00:00+07:00'),event={deviceId:'JR-GATE-01',eventId:'scan-001',employeeId:'12',occurredAt:'2026-09-22T08:06:00+07:00',eventType:'check_in'};
let preview=ctx.previewBiometricAttendanceEvent(event,now);assert.equal(preview.previewOnly,true);assert.equal(preview.kpi.points,1);assert.equal(existing,null);count++;
existing=preview.record;assert.equal(ctx.previewBiometricAttendanceEvent(event,now).duplicate,true);assert.equal(ctx.previewBiometricAttendanceEvent({...event,eventId:'scan-002',occurredAt:'2026-09-22T08:40:00+07:00'},now).record.checkIn,existing.checkIn);count+=2;existing=null;
preview=ctx.previewBiometricAttendanceEvent({...event,employeeId:'14',occurredAt:'2026-09-22T01:00:00+07:00'},now);assert.equal(preview.record.date,'2026-09-21');assert.equal(preview.kpi.points,3);count++;
assert.equal(ctx.previewBiometricAttendanceEvent({...event,eventType:'check_out'},now).ignored,true);count++;
for(const patch of [{employeeId:'999'},{employeeId:'0012'},{occurredAt:'2026-09-22T08:06:00'},{occurredAt:'2026-09-23T08:06:00+07:00'},{deviceId:'bad/path'},{eventId:''},{eventType:'unknown'}]){assert.throws(()=>ctx.previewBiometricAttendanceEvent({...event,...patch},now));count++}
for(const exception of [{type:'leave',leaveType:'personal'},{type:'absent',manualAdmin:true}]){existing={...base,exception};assert.equal(ctx.previewBiometricAttendanceEvent(event,now).requiresReview,true);count++}
existing=null;ctx.attendanceRecordBlockedByDeletion=()=>true;assert.throws(()=>ctx.previewBiometricAttendanceEvent(event,now));count++;
console.log(`${count} Attendance policy, boundary and biometric adapter scenarios passed`);
